{
 "title": "My App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Devices (Gauge)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "myapp_connected_devices", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "App Version (Gauge)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Upgrades (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(myapp_device_upgrade_total[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Latency (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency (Summary)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}